### PR TITLE
Add appendOOO method

### PR DESCRIPTION
**Pull request by arj03**
This allows a partial sequence of messages of a feed to be validated

### CODE REVIEW

**Comment by dominictarr** [comment]
how do you intend this to be used? can you give me some more context?

**Comment by arj03** [comment]
From what I can see, ooo messages are not checked [before](https://github.com/ssbc/ssb-ooo/blob/master/index.js#L75) written to db? That would be one case.

The reason I found it, was that I'm testing initial replication and wanted to play around with only received partial feeds. I actually got a minimal secret stack with flume-aligned-offset db, including backlinks & query working in the browser. Still very much WIP, but on git-ssb here ssb://%jfJAj+ssx9p9N85IN3Y00e3mXPqyYHKhShTeNwMap1w=.sha256 if you're interested. Took some stuff from the browser branch of ssb-db. I'll show you in Hamburg :)

**Comment by dominictarr** [comment]
ooo messages only check the hash. since you only get ooo messages if another message linked to them, then you know that it's definitely the message they replied to, it's still secure even if the private key is lost.

I put it in a separate log file, because putting it in the same would break some things, specifically clock and latest indexes, which are needed for replication.

**Comment by arj03** [comment]
> ooo messages only check the hash. since you only get ooo messages if another message linked to them, then you know that it's definitely the message they replied to, it's still secure even if the private key is lost.

Right, but I could create a message that looks as if you wrote it. Put that into my ooo db, create a new account that links to the fake message by hash. Since the signature on the fake message is never validated my guess is that this would work?

> I put it in a separate log file, because putting it in the same would break some things, specifically clock and latest indexes, which are needed for replication.

Yes, I understand the reason for doing ooo this way. I just wanted to play around with different ways of replicating data.

**Comment by arj03** [comment]
Yes this is still relavant

**Comment by arj03** [comment]
And the repo that demonstrates the problem https://github.com/arj03/ooo-hack

**Comment by christianbundy** [comment]
I'd support this PR. Anything I can do to help move it forward?

**Comment by arj03** [comment]
@christianbundy You can! :)

See if the repo I linked to makes sense. The problem this is trying to put light to is actually [this](https://github.com/ssbc/ssb-ooo/blob/master/index.js#L55) line in ssb-ooo. 

I also use this in [ssb-browser-demo](https://github.com/arj03/ssb-browser-demo).

**Comment by arj03** [comment]
For future travelers: The intention is to have a method that allows one to verify a specific message without having the verify all the previous messages. Basically this verifies everything about a message except the back pointer. From this one can verify later messages using the normal methods.

**Comment by christianbundy** [comment]
:tada:

**Pull request merged**
