### PR TITLE
remote the monotonic timestamp requirement

### LINKED ISSUE #2: Always increasing timestamps requirement
So it appears that I don't see messages from elavoie because of this:

[%25cKrjKrl8vL4w2BPeLc3X4EHpobTzqf36Vw%2BfnyHpjNk%3D.sha256](
http://between-two-worlds.dk:8807/%25cKrjKrl8vL4w2BPeLc3X4EHpobTzqf36Vw%2BfnyHpjNk%3D.sha256)

Kindly debugging by @ahdinosaur. 

The problematic line is: https://github.com/ssbc/ssb-validate/blob/master/index.js#L93

Which means that the message won't validate and won't be replicated. Its similar to the problem I was facing where my messages were not being replicated because the signature did not check out. It's actually not very easy to figure this out, you might first realize it when no-one replies to the things you are saying. Right now you need to run EBT with debugging to see what the problem is. Should this be a warning instead?

### PR DESCRIPTION
**Pull request by arj03**
This closes #2 and superseeds #5

### CODE REVIEW

**Comment by arj03** [comment]
@dominictarr if you give this a nod I'll merge and create a new release.

**Comment by dominictarr** [comment]
okay, looks good. please link into secure-scuttlebutt and scuttlebot and run tests (just to be sure, pretty sure this won't effect anything but as a best practice)

**Comment by arj03** [comment]
Tests in both secure-scuttebutt and scuttlebot passes. I'm releasing this. Thanks for the nod.

**Comment by arj03** [comment]
Not able to npm publish, can you add me as owner @dominictarr? Thanks :)

**Comment by dominictarr** [comment]
sorry, added you!

**Pull request merged**
