### PR TITLE
tests for valid messages now also check the id of that message is cor…

### PR DESCRIPTION
**Pull request by dominictarr**
added this for @bl0x to ensure that the test data covered the legacy hashing quirks for message ids.
as mentioned in this issue: https://github.com/ssbc/ssb-server/issues/696

`test/data/test_messages.json` now includes an `id` property, which is what the id should be. there is also hash field, which is the sha256 hash of the bytes of the stringification. If the message contains non-ascii these will be different, as they are in the case of the last message.

### CODE REVIEW

**Comment by bl0x** [comment]
@dominictarr : The commit removes all the 'cap' entries. Was that intentional? Now one cannot verify the signatures in all cases.

**Comment by dominictarr** [comment]
oh dear. because the tests are passing... they shouldn't be passing if they are ignoring the cap.
good spotting @bl0x !

the false positive was because it was calling `validate(state, cap, msg)` but validate actually expects a `validate(state, cap, feed_id)` it was acting as if it was an unknown feed id. added a commit to make that throw.

also, fixed the tests, they definitely check the signatures now, and caps are preserved.

**Comment by dominictarr** [comment]
weird the travis build failed with:

```
npm ERR! Error: No compatible version found: is-canonical-base64@'^1.1.1'
npm ERR! Valid install targets:
npm ERR! ["1.1.1"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
```

hmm, I notice the deps are a bit weird too

**Comment by dominictarr** [comment]
okay everything should be good now

**Comment by dominictarr** [comment]
uh no it has some problem with npm... but it's a really old npm, just gonna update it...

**Comment by dominictarr** [comment]
I mean drop old versions of node

**Comment by bl0x** [comment]
@dominictarr Great! Now I can validate all messages accordingly taking their IDs into account. Thanks for fixing this up.

**Comment by dominictarr** [comment]
@bl0x no problem, please keep us posted how your implementation is going!

**Comment by christianbundy** [comment]
Cool! Is this ready for a review? Couldn't tell by the comments and wanted to make sure it was ready before diving in.

**Pull request merged**
