### PR TITLE
fix: accept only objects and strings

### PR DESCRIPTION
**Pull request by noffle**
Before this would refuse strings, preventing private messages from being published.

### CODE REVIEW

**Comment by Happy0** [comment]
Copied from my scuttlebutt comment:

Looks good to me.

I checked out your fix-for-private-msgs branch for your pull request, and npm linked it into patchbay on its ,scuttlebot11 branch and now I can post chat messages in ssb-chess again :)

**Comment by noffle** [comment]
@Happy0 do you have npm permissions? I cannot publish. But I did push the `3.0.5` tag.

**Comment by noffle** [comment]
ping #dominictarr for

1. publish 3.0.5 to npm
2. add this module to the ssbc npm org

**Comment by noffle** [comment]
whoops @dominictarr

**Comment by mixmix** [comment]
I need to learn how to add modules to npm org, I've looked but not been able to see how to do it. If there's a permission thing on that would love to be able to have powers to help maintain npm state

**Comment by dominictarr** [comment]
this really needs more tests. fixed in 3.0.6 (and published)

**Comment by dominictarr** [comment]
sorry, I meant past tense: _needed more tests_ which it now has.

**Pull request merged**
